name: Python CI Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: echo "Installing dependencies..."

    build:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Build application
              run: echo "Building the application..."

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Test application
              run: echo "Testing the application..."

    deploy:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Deploy application
              run: echo "Deploying the application..."
